---
- name: Install nginx package
  yum: name="{{ item }}" state=present
  with_items:
    - epel-release
    - nginx

- name: Start and enable nginx
  service: name=nginx state=started enabled=yes

- name: Install nginx configuration file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload_nginx  

- name: Open http and https ports in firewall
  firewalld: service="{{ item }}" zone=public permanent=true state=enabled
  with_items: ['http', 'https']
  notify: reload_firewalld


